#!/bin/sh
PACKAGE_ARCH=$(echo "$DOCKER_TAG" | cut -d "-" -f1)
DSM_VER=$(echo "$DOCKER_TAG" | cut -d "-" -f2)

if [ "$DOCKER_TAG" = "latest" ]
then
  docker build . -t "${IMAGE_NAME}"
else
  docker run \
      --rm \
      --privileged \
      --env PACKAGE_ARCH="${PACKAGE_ARCH}" \
      --env DSM_VER="${DSM_VER}" \
      -v $(pwd)/artifacts:/result_spk \
      -v $(pwd)/toolkit_tarballs:/toolkit_tarballs \
      -t \
      "$DOCKER_REPO"
  docker build . -v $(pwd)/artifacts:/result_spk -t "${IMAGE_NAME}"
fi
