#!/bin/sh
PACKAGE_ARCH=$(echo "$DOCKER_TAG" | cut -d "-" -f1)
DSM_VER=$(echo "$DOCKER_TAG" | cut -d "-" -f2)

if [ "$DOCKER_TAG" = "latest" ]
then
  docker build . -t "${IMAGE_NAME}"
else
  docker run \
      --rm \
      --privileged \
      --env PACKAGE_ARCH=$arch \
      --env DSM_VER=$VER \
      -v $(pwd)/artifacts:/result_spk \
      -v $(pwd)/toolkit_tarballs:/toolkit_tarballs \
      "$DOCKER_REPO"
  docker build . --build-arg PACKAGE_ARCH="${PACKAGE_ARCH}" --build-arg DSM_VER="${DSM_VER}" -t "${IMAGE_NAME}" --privileged
fi
